version: "3.9"
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379" # remove me in prod
    volumes:
      -  dbvolume:/data
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432" # remove me in prod
    volumes:
      - pgvolume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  gameserver:
    build: gameserver
    restart: always
    ports:
      - "5000:5000" # remove me in prod
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - gamenet
  webserver:
    build: webserver
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - "80:80"
    env_file:
      - webserver.env
    environment:
      WEBSERVER_API_KEY: $WEBSERVER_API_KEY
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      GITSERVER_HOST: gitserver
      GITSERVER_HTTP_PORT: 2223
  gitserver:
    build: gitserver
    restart: always
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - git-repos:/app/repos
      - git-keys:/app/keys
    depends_on:
      - webserver
    environment:
      WEBSERVER_API_KEY: $WEBSERVER_API_KEY
      WEBSERVER_HOST: webserver
  botbuilder:
    build: botbuilder 
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    environment:
      WEBSERVER_API_KEY: $WEBSERVER_API_KEY
      WEBSERVER_HOST: webserver
      GITSERVER_HOST: gitserver
      GITSERVER_PORT: 2222
  scoreserver:
    build: scoreserver
    restart: always
    depends_on:
      - gameserver
      - redis

networks:
  gamenet:
    name: gamenet # needs to have an explicit name to attach the bot containers
    internal: true

volumes:
  git-repos:
  git-keys:
  dbvolume:
  pgvolume:
