version: "3.9"
services:
  redis:
    image: redis
  gameserver:
    build: gameserver
    ports:
      - 5000:5000
    depends_on:
      - redis
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - gamenet
  webserver:
    build: webserver
    ports:
      - 80:80
    depends_on:
      - redis
networks:
  gamenet:
    external: true