version: "3.9"
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379" # remove me in prod
    volumes:
      -  dbvolume:/data
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432" # remove me in prod
    volumes:
      - pgvolume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  gameserver:
    build: gameserver
    restart: always
    ports:
      - "5000:5000" # remove me in prod
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - gamenet
  webserver:
    build: webserver
    restart: always
    depends_on:
      - redis
    ports:
      - "80:80"
    env_file:
      - webserver.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  gitserver:
    build: gitserver
    restart: always
    ports:
      - "2222:2222"
    volumes:
      - git-repos:/app/repos
      - git-keys:/app/keys
    depends_on:
      - webserver
  botbuilder:
    build: botbuilder 
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
  scoreserver:
    build: scoreserver
    restart: always
    depends_on:
      - gameserver
      - redis

networks:
  gamenet:
    external: true
volumes:
  git-repos:
  git-keys:
  dbvolume:
  pgvolume:
