version: "3.9"
services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379" # remove me in prod
    volumes:
      -  dbvolume:/data
  gameserver:
    build: gameserver
    restart: unless-stopped
    ports:
      - "5000:5000" # remove me in prod
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - gamenet
  webserver:
    build: webserver
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "80:80"
    env_file:
      - webserver.env
  gitserver:
    build: gitserver
    restart: unless-stopped
    ports:
      - "2222:22"
    volumes:
      - botvolume:/git
      - githome:/home/
      - gitopt:/opt
      - botbuilder-notify:/botbuilder
    depends_on:
      - redis
  botbuilder:
    build: botbuilder 
    restart: unless-stopped
    volumes:
      - botbuilder-notify:/botbuilder
      - botvolume:/git
      - /var/run/docker.sock:/var/run/docker.sock
  scoreserver:
    build: scoreserver
    restart: unless-stopped
    depends_on:
      - gameserver
      - redis

networks:
  gamenet:
    external: true
volumes:
  botvolume:
  githome:
  gitopt:
  botbuilder-notify:
  dbvolume:
  letsencrypt:
