"""unique ssh public key column

Revision ID: 7aa56bc6afae
Revises: 66d2f2e1ccb2
Create Date: 2021-12-27 01:29:16.870793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa56bc6afae'
down_revision = '66d2f2e1ccb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['ssh_public_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
