"""remove repo table

Revision ID: d83131755ec8
Revises: c800f5c65a0f
Create Date: 2021-12-27 16:29:09.007446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd83131755ec8'
down_revision = 'c800f5c65a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_repositories_id', table_name='repositories')
    op.drop_index('ix_repositories_name', table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('owner_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='repositories_owner_id_fkey')
    )
    op.create_index('ix_repositories_name', 'repositories', ['name'], unique=False)
    op.create_index('ix_repositories_id', 'repositories', ['id'], unique=False)
    # ### end Alembic commands ###
